name: $(Build.SourceBranchName)-$(Build.SourceVersion)

resources:
  - repo: self

trigger:
  - master
  - bryphe/*
  - andreypopp/*

jobs:
  - job: buildLinux
    displayName: Build Linux
    condition: succeeded()
    pool:
        vmImage: ubuntu-16.04

    variables:
        STAGING_DIRECTORY: /home/vsts/STAGING
        STAGING_DIRECTORY_UNIX: /home/vsts/STAGING
        ESY__CACHE_INSTALL_PATH: /home/vsts/.esy/3_____________________________________________________________________/i
        ESY__CACHE_SOURCE_TARBALL_PATH: /home/vsts/.esy/source/i
        # ESY__NPM_ROOT: /opt/hostedtoolcache/node/8.14.0/x64/lib/node_modules/esy

    steps:
      - script: sudo apt-get update
      - script: sudo apt-get install -y libcurl4-gnutls-dev libssl-dev libgmp-dev
      - template: use-node.yml
      - template: restore-build-cache.yml
      - template: build.yml
      - template: publish-build-cache.yml

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Platform Release'
        inputs:
          PathtoPublish: '_platformrelease'
          ArtifactName: platform-linux

  - job: buildMacos
    displayName: Build macOS
    condition: succeeded()
    pool:
      vmImage: macOS-10.13
      demands: node.js

    variables:
        HOMEBREW_NO_AUTO_UPDATE: yes
        STAGING_DIRECTORY: /Users/vsts/STAGING
        STAGING_DIRECTORY_UNIX: /Users/vsts/STAGING
        ESY__CACHE_INSTALL_PATH: /Users/vsts/.esy/3____________________________________________________________________/i
        ESY__CACHE_SOURCE_TARBALL_PATH: /Users/vsts/.esy/source/i
        # ESY__NPM_ROOT: /usr/local/lib/node_modules/esy

    steps:
      - script: brew install gmp
      - template: use-node.yml
      - template: restore-build-cache.yml
      - template: build.yml
      - template: publish-build-cache.yml

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Platform Release'
        inputs:
          PathtoPublish: '_platformrelease'
          ArtifactName: platform-darwin

  - job: buildWindows
    displayName: Windows
    condition: succeeded()
    timeoutInMinutes: 0
    pool:
      vmImage: vs2017-win2016
      demands: npm

    variables:
        STAGING_DIRECTORY: C:\Users\VssAdministrator\STAGING
        STAGING_DIRECTORY_UNIX: /C/Users/VssAdministrator/STAGING
        ESY__CACHE_INSTALL_PATH: /C/Users/VssAdministrator/.esy/3_/i
        ESY__CACHE_SOURCE_TARBALL_PATH: /C/Users/VssAdministrator/.esy/source/i
        # ESY__NPM_ROOT: /C/npm/prefix/node_modules/esy

    steps:
      - template: use-node.yml
      - template: restore-build-cache.yml
      - template: build.yml
      - template: publish-build-cache.yml

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: Windows'
        inputs:
          PathtoPublish: '_platformrelease'
          ArtifactName: platform-win32

  - job: buildRelease
    displayName: Build Release
    dependsOn:
      - buildLinux
      - buildMacos
      - buildWindows
    condition: succeeded()
    pool:
      vmImage: ubuntu-16.04

    steps:

    - script: |
        node scripts/make-release-skeleton.js
      displayName: 'Prepare release'

    - task: DownloadBuildArtifacts@0
      displayName: 'Download Linux Artifacts'
      inputs:
        artifactName: platform-linux
        downloadPath: '_release'

    - task: DownloadBuildArtifacts@0
      displayName: 'Download macOS Artifacts'
      inputs:
        artifactName: platform-darwin
        downloadPath: '_release'

    - task: DownloadBuildArtifacts@0
      displayName: 'Download Windows Artifacts'
      inputs:
        artifactName: platform-win32
        downloadPath: '_release'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: Release'
      inputs:
        PathtoPublish: '_release'
        ArtifactName: release
