name: Build npm release

resources:
  - repo: self

trigger:
  - master

jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-16.04

    steps:
      - template: build-nix.yml

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: Linux'
        inputs:
          PathtoPublish: '_platformrelease'
          ArtifactName: Linux

  - job: macOS
    pool:
      vmImage: macOS-10.13
      demands: node.js

    steps:
      - template: build-nix.yml

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: macOS'
        inputs:
          PathtoPublish: '_platformrelease'
          ArtifactName: macOS

  - job: Windows
    pool:
      timeoutInMinutes: 120
      vmImage: vs2017-win2016
      demands: npm

    steps:
      - template: build-windows.yml

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: Windows'
        inputs:
          PathtoPublish: '_platformrelease'
          ArtifactName: Windows

  - job: Release
    displayName: Release
    dependsOn:
      - Linux
      - macOS
      - Windows

    pool:
      vmImage: ubuntu-16.04

    steps:
      - template: release.yml

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: Release'
        inputs:
          PathtoPublish: '_release'
          ArtifactName: Release

  - job: TestInstallLinux
    displayName: Test install Linux
    dependsOn:
      - Release

    pool:
      vmImage: ubuntu-16.04

    steps:
      - task: DownloadBuildArtifacts@0
        displayName: 'Download release'
        inputs:
          artifactName: Release
          downloadPath: 'release'

      - script: 'npm i -g ./esy-*.tgz'
        displayName: 'install release'
        workingDirectory: 'release'

      - script: 'esy --help'
        displayName: 'esy --help'

  - job: TestInstallmacOS
    displayName: Test install macOS
    dependsOn:
      - Release

    pool:
      vmImage: macOS-10.13
      demands: node.js

    steps:
      - task: DownloadBuildArtifacts@0
        displayName: 'Download release'
        inputs:
          artifactName: Release
          downloadPath: 'release'

      - script: 'npm i -g ./esy-*.tgz'
        displayName: 'install release'
        workingDirectory: 'release'

      - script: 'esy --help'
        displayName: 'esy --help'

  - job: TestInstallWindows
    displayName: Test install Windows
    dependsOn:
      - Release

    pool:
      vmImage: vs2017-win2016
      demands: npm

    steps:
      - task: DownloadBuildArtifacts@0
        displayName: 'Download release'
        inputs:
          artifactName: Release
          downloadPath: 'release'

      - script: 'npm i -g ./esy-*.tgz'
        displayName: 'install release'
        workingDirectory: 'release'

      - script: 'esy --help'
        displayName: 'esy --help'
