name: Build npm release
pool:
  timeoutInMinutes: 120

resources:
  - repo: self

trigger:
  - master

phases:
  - phase: Phase_1
    displayName: Linux
    condition: succeeded()
    queue:
      name: Hosted Ubuntu 1604

    steps:
      - template: build-nix.yml

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: Linux'
        inputs:
          PathtoPublish: '_platformrelease'
          ArtifactName: Linux

  - phase: Phase_2
    displayName: macOS
    condition: succeeded()
    queue:
      name: Hosted macOS
      demands: node.js

    steps:
      - template: build-nix.yml

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: macOS'
        inputs:
          PathtoPublish: '_platformrelease'
          ArtifactName: macOS

  - phase: Phase_3
    displayName: Windows
    condition: succeeded()
    queue:
      name: Hosted VS2017
      demands: npm

    steps:
      - template: build-windows.yml

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: Windows'
        inputs:
          PathtoPublish: '_platformrelease'
          ArtifactName: Windows

  - phase: Phase_4
    displayName: Agent job
    dependsOn:
      - Phase_1
      - Phase_2
      - Phase_3
    condition: succeeded()
    queue:
      name: Hosted Ubuntu 1604
    steps:
      - task: DownloadBuildArtifacts@0
        displayName: 'Download Linux Artifacts'
        inputs:
          artifactName: Linux
          downloadPath: '_release'

      - script: 'mkdir _release/platform-linux'
        displayName: 'Create _release/platform-linux'

      - script: 'tar -xzf _release/Linux/*.tgz -C _release/platform-linux'
        displayName: 'untar Linux'

      - script: 'rm -rf _release/Linux'
        displayName: 'Remove Linux artifacts'

      - task: DownloadBuildArtifacts@0
        displayName: 'Download macOS Artifacts'
        inputs:
          artifactName: macOS
          downloadPath: '_release'

      - script: 'mkdir _release/platform-darwin'
        displayName: 'Create _release/platform-darwin'

      - script: 'tar -xzf _release/macOS/*.tgz -C _release/platform-darwin'
        displayName: 'untar macOS'

      - script: 'rm -rf _release/macOS'
        displayName: 'Remove macOS artifacts'

      - task: DownloadBuildArtifacts@0
        displayName: 'Download Windows Artifacts'
        inputs:
          artifactName: Windows
          downloadPath: '_release'
        continueOnError: true

      - script: 'mkdir _release/platform-windows-x64'
        displayName: 'Create _release/platform-windows-x64'
        continueOnError: true

      - script: 'tar -xzf _release/Windows/*.tgz -C _release/platform-windows-x64'
        displayName: 'untar Windows'
        continueOnError: true

      - script: 'rm -rf _release/Windows'
        displayName: 'Remove Windows artifacts'
        continueOnError: true

      - script: 'cp LICENSE _release/LICENSE'
        displayName: 'copy LICENSE'

      - script: 'cp README.md _release/README.md'
        displayName: 'copy README.md'

      - script: 'cp scripts/release-postinstall.js _release/postinstall.js'
        displayName: 'copy postinstall.js'

      - script: 'node scripts/create-release-package-json.js > _release/package.json'
        displayName: 'Create package.json'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: Release'
        inputs:
          PathtoPublish: '_release'
          ArtifactName: Release
